//! Optional differential corpus generated by the supplied Python detector.
//! Set LTBOX_EFISP_CORPUS to a JSON array of {"path": "...", "verdict": "..."}
//! and run cargo test -p ltbox-patch --test efisp_load_fixtures -- --ignored.
use ltbox_patch::efisp_load::{EfispLoad, detect};

#[test]
#[ignore = "requires a local corpus labelled by check_efisp_load.py"]
fn matches_python_labelled_abl_corpus() {
    let manifest = std::env::var_os("LTBOX_EFISP_CORPUS").expect("set LTBOX_EFISP_CORPUS");
    let cases: Vec<serde_json::Value> =
        serde_json::from_slice(&std::fs::read(manifest).unwrap()).unwrap();
    assert!(!cases.is_empty());
    for case in cases {
        let path = case["path"].as_str().unwrap();
        let expected = match case["verdict"].as_str().unwrap() {
            "VULNERABLE" => EfispLoad::Yes,
            "PATCHED" => EfispLoad::No,
            "AUTH-GATED" | "ERROR" => EfispLoad::Undetermined,
            other => panic!("unrecognised reference verdict {other}"),
        };
        assert_eq!(detect(&std::fs::read(path).unwrap()), expected, "{path}");
    }
}
